const userConstants = {
    LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    LOGIN_FAIL: 'USER_LOGIN_FAIL',
    JOIN_REQUEST: 'USER_JOIN_REQUEST',
    JOIN_SUCCESS: 'USER_JOIN_SUCCESS',
    JOIN_FAIL: 'USER_JOIN_FAIL'
}
export default userConstants